In [1]:
import polars as pl

In [21]:
hrv_freq = pl.read_csv("../../data/HRV/frequency_domain.csv")
hrv_freq = hrv_freq.with_columns(pl.col("date").str.strptime(pl.Date, "%Y-%m-%d")) # you may have to change format of date
hrv_freq = hrv_freq.with_columns((pl.col("LF") / pl.col("HF")).alias("LFHFratio"))
hrv_freq

shape: (2_332, 5)
┌────────────┬─────────────┬─────────────┬────────────┬───────────┐
│ date       ┆ VLF         ┆ LF          ┆ HF         ┆ LFHFratio │
│ ---        ┆ ---         ┆ ---         ┆ ---        ┆ ---       │
│ date       ┆ f64         ┆ f64         ┆ f64        ┆ f64       │
╞════════════╪═════════════╪═════════════╪════════════╪═══════════╡
│ 2017-07-24 ┆ 884.554467  ┆ 176.079683  ┆ 98.624315  ┆ 1.785358  │
│ 2017-07-25 ┆ 1077.163019 ┆ 409.565229  ┆ 692.82705  ┆ 0.591151  │
│ 2017-07-26 ┆ 833.683813  ┆ 284.855324  ┆ 167.546255 ┆ 1.700159  │
│ 2017-07-27 ┆ 1636.069588 ┆ 293.085583  ┆ 222.901403 ┆ 1.314866  │
│ 2017-07-28 ┆ 994.366727  ┆ 335.918425  ┆ 517.969574 ┆ 0.648529  │
│ …          ┆ …           ┆ …           ┆ …          ┆ …         │
│ 2024-07-27 ┆ 515.231496  ┆ 96.740276   ┆ 91.897295  ┆ 1.0527    │
│ 2024-07-28 ┆ 379.673057  ┆ 56.757491   ┆ 74.488373  ┆ 0.761964  │
│ 2024-07-29 ┆ 345.60592   ┆ 138.035528  ┆ 166.064964 ┆ 0.831214  │
│ 2024-07-30 ┆ 1241.925347 ┆ 184.857937  ┆ 119.186683 ┆ 1.550995  │
│ 2024-07-31 ┆ 1685.192154 ┆ 2412.622505 ┆ 299.051195 ┆ 8.06759   │
└────────────┴─────────────┴─────────────┴────────────┴───────────┘

In [22]:
hrv_freq.null_count()

shape: (1, 5)
┌──────┬─────┬─────┬─────┬───────────┐
│ date ┆ VLF ┆ LF  ┆ HF  ┆ LFHFratio │
│ ---  ┆ --- ┆ --- ┆ --- ┆ ---       │
│ u32  ┆ u32 ┆ u32 ┆ u32 ┆ u32       │
╞══════╪═════╪═════╪═════╪═══════════╡
│ 0    ┆ 0   ┆ 0   ┆ 0   ┆ 0         │
└──────┴─────┴─────┴─────┴───────────┘

In [24]:
hrv_tnl = pl.read_csv("../../data/HRV/time_nonlinear_domain.csv")
hrv_tnl = hrv_tnl.with_columns(pl.col("date").str.strptime(pl.Date, "%Y-%m-%d")) # you may have to change format of date
hrv_tnl = hrv_tnl.drop("mean_RRI")
hrv_tnl

shape: (2_332, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ date      ┆ HR        ┆ SDNN      ┆ RMSSD     ┆ … ┆ ApEn     ┆ SD1       ┆ SD2       ┆ SD1SD2rat │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ---       ┆ ---       ┆ io        │
│ date      ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64      ┆ f64       ┆ f64       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 2017-07-2 ┆ 89.918794 ┆ 50.293799 ┆ 20.861884 ┆ … ┆ 0.922786 ┆ 14.75156  ┆ 69.499062 ┆ 0.212256  │
│ 4         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2017-07-2 ┆ 88.932674 ┆ 60.827421 ┆ 57.237082 ┆ … ┆ 0.901482 ┆ 40.472728 ┆ 75.529353 ┆ 0.535854  │
│ 5         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2017-07-2 ┆ 93.593945 ┆ 51.727819 ┆ 27.178771 ┆ … ┆ 0.634698 ┆ 19.218055 ┆ 70.521594 ┆ 0.272513  │
│ 6         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2017-07-2 ┆ 83.92394  ┆ 75.542652 ┆ 38.155843 ┆ … ┆ 0.728771 ┆ 26.979802 ┆ 102.90532 ┆ 0.262181  │
│ 7         ┆           ┆           ┆           ┆   ┆          ┆           ┆ 3         ┆           │
│ 2017-07-2 ┆ 90.402819 ┆ 59.249159 ┆ 41.522311 ┆ … ┆ 0.58117  ┆ 29.360692 ┆ 78.456813 ┆ 0.374227  │
│ 8         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 2024-07-2 ┆ 89.893828 ┆ 53.719479 ┆ 25.677184 ┆ … ┆ 0.88455  ┆ 18.152919 ┆ 70.733274 ┆ 0.256639  │
│ 7         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2024-07-2 ┆ 91.968662 ┆ 35.336093 ┆ 21.310553 ┆ … ┆ 1.0956   ┆ 15.068741 ┆ 47.584775 ┆ 0.316671  │
│ 8         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2024-07-2 ┆ 94.749657 ┆ 46.302269 ┆ 40.420499 ┆ … ┆ 0.872807 ┆ 28.581471 ┆ 58.754495 ┆ 0.486456  │
│ 9         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2024-07-3 ┆ 84.314767 ┆ 47.685605 ┆ 20.473028 ┆ … ┆ 1.136272 ┆ 14.476398 ┆ 65.826789 ┆ 0.219917  │
│ 0         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2024-07-3 ┆ 80.377813 ┆ 48.672316 ┆ 31.250593 ┆ … ┆ 1.121821 ┆ 22.097101 ┆ 65.038771 ┆ 0.339753  │
│ 1         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [25]:
hrv_tnl.null_count()

shape: (1, 11)
┌──────┬─────┬──────┬───────┬───┬──────┬─────┬─────┬─────────────┐
│ date ┆ HR  ┆ SDNN ┆ RMSSD ┆ … ┆ ApEn ┆ SD1 ┆ SD2 ┆ SD1SD2ratio │
│ ---  ┆ --- ┆ ---  ┆ ---   ┆   ┆ ---  ┆ --- ┆ --- ┆ ---         │
│ u32  ┆ u32 ┆ u32  ┆ u32   ┆   ┆ u32  ┆ u32 ┆ u32 ┆ u32         │
╞══════╪═════╪══════╪═══════╪═══╪══════╪═════╪═════╪═════════════╡
│ 0    ┆ 0   ┆ 0    ┆ 0     ┆ … ┆ 0    ┆ 0   ┆ 0   ┆ 0           │
└──────┴─────┴──────┴───────┴───┴──────┴─────┴─────┴─────────────┘

In [27]:
hrv = hrv_freq.join(hrv_tnl, on="date")
hrv

shape: (2_332, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ date      ┆ VLF       ┆ LF        ┆ HF        ┆ … ┆ ApEn     ┆ SD1       ┆ SD2       ┆ SD1SD2rat │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ---       ┆ ---       ┆ io        │
│ date      ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64      ┆ f64       ┆ f64       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 2017-07-2 ┆ 884.55446 ┆ 176.07968 ┆ 98.624315 ┆ … ┆ 0.922786 ┆ 14.75156  ┆ 69.499062 ┆ 0.212256  │
│ 4         ┆ 7         ┆ 3         ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2017-07-2 ┆ 1077.1630 ┆ 409.56522 ┆ 692.82705 ┆ … ┆ 0.901482 ┆ 40.472728 ┆ 75.529353 ┆ 0.535854  │
│ 5         ┆ 19        ┆ 9         ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2017-07-2 ┆ 833.68381 ┆ 284.85532 ┆ 167.54625 ┆ … ┆ 0.634698 ┆ 19.218055 ┆ 70.521594 ┆ 0.272513  │
│ 6         ┆ 3         ┆ 4         ┆ 5         ┆   ┆          ┆           ┆           ┆           │
│ 2017-07-2 ┆ 1636.0695 ┆ 293.08558 ┆ 222.90140 ┆ … ┆ 0.728771 ┆ 26.979802 ┆ 102.90532 ┆ 0.262181  │
│ 7         ┆ 88        ┆ 3         ┆ 3         ┆   ┆          ┆           ┆ 3         ┆           │
│ 2017-07-2 ┆ 994.36672 ┆ 335.91842 ┆ 517.96957 ┆ … ┆ 0.58117  ┆ 29.360692 ┆ 78.456813 ┆ 0.374227  │
│ 8         ┆ 7         ┆ 5         ┆ 4         ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 2024-07-2 ┆ 515.23149 ┆ 96.740276 ┆ 91.897295 ┆ … ┆ 0.88455  ┆ 18.152919 ┆ 70.733274 ┆ 0.256639  │
│ 7         ┆ 6         ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2024-07-2 ┆ 379.67305 ┆ 56.757491 ┆ 74.488373 ┆ … ┆ 1.0956   ┆ 15.068741 ┆ 47.584775 ┆ 0.316671  │
│ 8         ┆ 7         ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2024-07-2 ┆ 345.60592 ┆ 138.03552 ┆ 166.06496 ┆ … ┆ 0.872807 ┆ 28.581471 ┆ 58.754495 ┆ 0.486456  │
│ 9         ┆           ┆ 8         ┆ 4         ┆   ┆          ┆           ┆           ┆           │
│ 2024-07-3 ┆ 1241.9253 ┆ 184.85793 ┆ 119.18668 ┆ … ┆ 1.136272 ┆ 14.476398 ┆ 65.826789 ┆ 0.219917  │
│ 0         ┆ 47        ┆ 7         ┆ 3         ┆   ┆          ┆           ┆           ┆           │
│ 2024-07-3 ┆ 1685.1921 ┆ 2412.6225 ┆ 299.05119 ┆ … ┆ 1.121821 ┆ 22.097101 ┆ 65.038771 ┆ 0.339753  │
│ 1         ┆ 54        ┆ 05        ┆ 5         ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [28]:
hrv.write_csv("../../data/HRV/hrv.csv")

---
## Check missing date

In [30]:
from datetime import date
d = pl.DataFrame(pl.date_range(date(2017, 7, 24), date(2024, 7, 31), eager=True).alias("date"))
missing_d = d.join(hrv, on="date", how="anti")
missing_d

shape: (233, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 2017-08-25 │
│ 2017-09-01 │
│ 2017-09-02 │
│ 2017-09-03 │
│ 2017-09-04 │
│ …          │
│ 2024-05-04 │
│ 2024-05-05 │
│ 2024-06-13 │
│ 2024-06-29 │
│ 2024-07-02 │
└────────────┘

---

---

add June and July data

time and non-linear domain

In [15]:
before = pl.read_csv("../../data/HRV/trash/time_nonlinear_domain_use_this.csv")
before = before.with_columns(pl.col("date").str.strptime(pl.Date, "%Y/%m/%d"))
june = pl.read_csv("../../data/HRV/trash/time_nonlinear_domain_2024_06.csv")
june = june.with_columns(pl.col("date").str.strptime(pl.Date, "%Y/%m/%d"))
july = pl.read_csv("../../data/HRV/trash/time_nonlinear_domain_2024_07.csv")
july = july.with_columns(pl.col("date").str.strptime(pl.Date, "%Y/%m/%d"))
pl.concat([before, june, july]).write_csv("../../data/HRV/time_nonlinear_domain.csv")

freq. domain

In [17]:
before = pl.read_csv("../../data/HRV/trash/freqency_domain_use_this.csv")
before = before.with_columns(pl.col("date").str.strptime(pl.Date, "%Y/%m/%d"))
june = pl.read_csv("../../data/HRV/trash/freq_06.csv")
june = june.with_columns(pl.col("date").str.strptime(pl.Date, "%Y/%m/%d"))
july = pl.read_csv("../../data/HRV/trash/freq_07.csv")
july = july.with_columns(pl.col("date").str.strptime(pl.Date, "%Y/%m/%d"))
pl.concat([before, june, july]).write_csv("../../data/HRV/frequency_domain.csv")